apiVersion: v1
kind: Secret
metadata:
  name: image-service
type: Opaque
data:
  AZURE_STORAGE_CONNECTION_STRING: "<secret>"
  DEFAULT_CONTAINER: "<secret>"
  # Formato: <cert_cn>:<api_key>  (base64)
  PROJECT_ALPHA: "<secret>"
  PROJECT_BETA: "<secret>"
